version: "3"
services:
  db:
    container_name: mydb
    image: mysql:latest
    ports: 
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
  app:
    container_name: myapp
    depends_on:
      - db
    build: ./
    ports:
      - "9091:9091"
    entrypoint: ["./utils/wait-for-it.sh", "mydb:3306", "--", "python", "main.py"]