version: "3"
services:
  db:
    env_file: ./configs/.env
    container_name: ${DB_HOST}
    image: mysql:8.0
    ports: 
      - ${DB_PORT}:${DB_PORT}
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
  app:
    container_name: ${APP_HOST}
    depends_on:
      - db
    build: ./
    ports:
      - ${APP_PORT}:${APP_PORT}
    entrypoint: ["./utils/wait-for-it.sh", "-t", "${DB_WAIT_TIMEOUT}", "${DB_HOST}:${DB_PORT}", "--", "python", "main.py"]