---
- hosts: web
  vars:
    ansible_python_interpreter: /usr/bin/python3.10
    github_repo_url: "https://github.com/CyrusChanDev/Python-Flask-URL-Shortener.git"
    github_token: "{{ lookup('file', '~/github_token.txt') }}"
  tasks:
    - name: Update apt
      apt:
        update_cache: yes
      become: yes

    - name: Install software
      apt:
        name: 
          - vim
          - git
          - docker-compose
          - python3-pip
          - docker.io
        state: present
      become: yes
    
    - name: Clone the GitHub repository
      git:
        repo: "https://{{ github_token }}@github.com/CyrusChanDev/Python-Flask-URL-Shortener.git"
        dest: /tmp/personal_project
        version: main

    - name: Setup application using Docker-compose
      shell: docker-compose -f /tmp/personal_project/docker-compose.yaml --env-file /tmp/personal_project/configs/.env up -d --build
      become: yes